refactor project structure

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,7 +9,6 @@ name: CI
     - cron: "0 5 * * 4"
 
 jobs:
-
   lint:
     name: Lint
     runs-on: ubuntu-latest
@@ -34,7 +33,7 @@ jobs:
     strategy:
       matrix:
         os:
-          - macos-10.15
+          - macos-latest
 
     steps:
       - name: Check out the codebase.
@@ -47,5 +46,22 @@ jobs:
         run: |
           sudo rm -rf /Applications/Firefox.app
           sudo rm -rf /Applications/Google\ Chrome.app
+
       - name: Install test dependencies.
         run: sudo pip3 install ansible
+
+      - name: Syntax check
+        run: ansible-playbook main.yml --syntax-check
+
+      - name: Test playbook
+        run: ansible-playbook main.yml -vvvv
+        env:
+          ANSIBLE_FORCE_COLOR: '1'
+
+      - name: Idempotence check
+        run: |
+          idempotence=$(mktemp)
+          ansible-playbook main.yml -vvvv | tee -a ${idempotence}
+          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
+        env:
+          ANSIBLE_FORCE_COLOR: '1'
